### ISSUE TITLE
Rewrite timers implementation

### ISSUE THREAD

**Issue by Thomasdezeeuw** [Thomasdezeeuw/heph#284]
The current one is very poor.

* [x] Local implementation, done in #422.
* [ ] Shared implementation.
* [x] Benchmark the number of slots in the timing wheel, moved to  #424.
* [x] Benchmark the number of nanoseconds per slot, moved to  #424.

**Comment by Thomasdezeeuw** [comment]
Related #315.
