### ISSUE TITLE
Additional testing

### ISSUE THREAD

**Issue by Thomasdezeeuw** [Thomasdezeeuw/heph#371]
The following things (types, function etc.) need additional testing.

* [x] `Bytes` trait and implementations, done in #427.
* [x] `BytesVectored` trait and implementations, done in #427.
* ~~[ ] `TcpStream::recv_n_vectored` with `BytesVectored` which doesn't update the lengths correctly using `BytesVectored::update_lengths`.~~ No longer valid since commits e1522011f8d65584e29cab8156915b54396598ec, c00cd77cc02cb76efb4ddd76361a662353018779.
* [x] `UdpSocket::local_addr`, done in #427.
* [x] `UdpSocket`'s  `actor::Bound` implementation, done in #427.
* [x] `ActorProcress::handle_restart_error`:
  * [x] return `ProcessResult::Pending`, done in #431.
  * [x] return `ProcessResult::Complete`, done in #431.
  * [x] Can we create a restart loop with an actor that crashes on first run and gets restarted without limitation. In `Process` for `ActorProcess` this run the actor -> error, which calls the supervisor, restarts and run the actor again. Documented in #431
* [x] Restarting thread-safe actor, done in #431.
* [x] Restarting sync actor, done in #427.
  * [x] Restarting.
  * [x] Stopping.
* [x] Signal handling:
  * [x] Received by thread-local actor, done in #431.
  * [x] Received by thread-safe actor, done in #431.
  * [x] Received by sync actor, done in #431.
  * [x] Received by no actors -> shutdown runtime, done in #431.
* ~~[ ] `shared::scheduler::Branch::add` `ReadyToRun` branch~~, no longer valid after #429.
* ~~[ ] `shared::scheduler::Branch::mark_ready` `ReadyToRun` branch~~, no longer valid after #429.
