### ISSUE TITLE
Fix flaky tests/examples

### ISSUE THREAD

**Issue by Thomasdezeeuw** [Thomasdezeeuw/heph#374]
There are a number of tests/examples that are a bit flaky:

* [x] Example 6 process signals test: no messages in output,, tests/examples.rs:72, fixed in #438.
* [x] Example 2 my ip: 'failed to connect to address', tests/examples.rs:197, fixed in #439.
* [ ] ~~functional::timer::timers_dont_trigger_after_actour_bound: 'expected pending, got `Poll::Ready(DeadlinePassed)`', tests/functional/timer.rs:443~~, can't reproduce.
* [x] functional::udp::actor_bound has been running for over 60 seconds, fixed in #435.
* [x] regression::issue_145::issue_145_tcp_server has been running for over 60 seconds, fixed in  #436.
* [x] src/actor_ref/rpc.rs - actor_ref::rpc (line 86) has been running for over 60 seconds, fixed in #437.

**Comment by Thomasdezeeuw** [comment]
Commit bdbece7 ignores the test as it's too flaky in the CI.

**Comment by Thomasdezeeuw** [comment]
I think this is because of the `SyncWaker` (`task::Waker` for sync actors) implementation.

**Comment by Thomasdezeeuw** [comment]
All issues are fixed.
